.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SCHOONER\-MULTIBALANCE" "1" "March 2015" "propublica" "schooner-tk"
.
.SH "NAME"
\fBschooner\-multibalance\fR \- color correct a batch of images
.
.SH "SYNOPSIS"
\fBschooner\-multibalance\fR [\fIdatasets\fR\.\.\.]
.
.SH "DESCRIPTION"
\fBschooner\-multibalance\fR automatically corrects each band of many datasets so that each dataset has a similar color profile\. This is useful as a preprocessing step to \fBschooner\-blend\fR\.
.
.SH "CAVEATS"
This tool operates in place and will change the source image, you probably want to create a backup of the source images\.
.
.SH "SEE ALSO"
schooner\-blend(1), schooner\-cloud(1), schooner\-contrast(1), schooner\-stitch(1)
